# fly.toml app configuration file generated for gleam-package-mcp on 2025-09-16

app = "gleam-package-mcp"
primary_region = "fra"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[env]
PORT = "3000"
XDG_DATA_HOME = "/data"
GLEAM_DOCS_CACHE = "/data/docs_cache"
MAX_INTERFACE_RESPONSE_SIZE = "20000"

[mounts]
source = "gleam_packages_data"
destination = "/data"
